package ServerApp;


/**
* ServerApp/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/alekh/Downloads/W-2019/6231/Assignments/Assignment2/DLMS_CORBA/src/idl/Server.idl
* Tuesday, February 26, 2019 10:32:32 o'clock AM EST
*/

public interface ServerOperations 
{
  String addItem (String managerID, String itemID, String itemName, int quantity);
  String removeItem (String managerID, String itemID, int quantity);
  String listItemAvailability (String managerID);

  //Operations performed by user
  String borrowItem (String userID, String itemID, boolean isWaitlisted);
  String findItem (String userID, String itemName);
  String returnItem (String userID, String itemID);
  String exchangeItem (String userID, String oldItemID, String newItemID);
} // interface ServerOperations
