package ServerApp;


/**
* ServerApp/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/alekh/Downloads/W-2019/6231/Assignments/Assignment2/DLMS_CORBA/src/idl/Server.idl
* Tuesday, February 26, 2019 10:32:32 o'clock AM EST
*/

public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
